table DimFacility
	lineageTag: 28fb01d4-9601-45b5-a451-424f78a4f732

	column facility_id
		dataType: string
		isNullable: false
		lineageTag: 1a5cdf56-34b5-4168-b411-381dfd0cf1fc
		summarizeBy: none
		sourceColumn: facility_id

		annotation SummarizationSetBy = Automatic

	column facility_name
		dataType: string
		isNullable: false
		lineageTag: 2ba25317-288b-4f41-a671-2ca8e34a8ac1
		summarizeBy: none
		sourceColumn: facility_name

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		isNullable: false
		lineageTag: fccbbf6b-a682-43d3-a6b0-d7ccdf1a39ff
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		isNullable: false
		lineageTag: 1b3782e9-5529-4295-8e65-a3b9e438ca18
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		isNullable: false
		lineageTag: ff9141e8-a17c-4077-8b42-06045e95f4f4
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column capacity_mw
		dataType: double
		isNullable: false
		lineageTag: 122b9aab-d487-46b9-9f61-e22edc2083de
		summarizeBy: none
		sourceColumn: capacity_mw

		annotation SummarizationSetBy = Automatic

	column rack_capacity
		dataType: int64
		isNullable: false
		lineageTag: c656880d-2627-49c8-82cb-d6b95565a12b
		summarizeBy: none
		sourceColumn: rack_capacity

		annotation SummarizationSetBy = Automatic

	column build_year
		dataType: int64
		isNullable: false
		lineageTag: a9a11319-4c54-4160-9110-bb2272725f14
		summarizeBy: none
		sourceColumn: build_year

		annotation SummarizationSetBy = Automatic

	column commission_date
		dataType: dateTime
		isNullable: false
		formatString: Long Date
		lineageTag: b967757e-4d63-4636-b17e-8dade43cf235
		summarizeBy: none
		sourceColumn: commission_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition DimFacility = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/admin/Downloads/AI_Image_Classification_Final_Project_Import_Fixed/ai-data-center-intelligence/data/processed/facilities.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"facility_id", type text}, {"facility_name", type text}, {"city", type text},
				        {"country", type text}, {"region", type text}, {"capacity_mw", type number},
				        {"rack_capacity", Int64.Type}, {"build_year", Int64.Type}, {"commission_date", type date}
				    })
				in
				    Typed

