table DimServer
	lineageTag: 1336c5eb-ab92-4f5e-a387-8b0da25a73a0

	column server_id
		dataType: string
		isNullable: false
		lineageTag: b824dcec-89e5-4e3f-8711-eb7cd4aa5b38
		summarizeBy: none
		sourceColumn: server_id

		annotation SummarizationSetBy = Automatic

	column facility_id
		dataType: string
		isNullable: false
		lineageTag: 3d990194-bf82-42c9-8d9b-9512ab981025
		summarizeBy: none
		sourceColumn: facility_id

		annotation SummarizationSetBy = Automatic

	column rack_id
		dataType: string
		isNullable: false
		lineageTag: a97979eb-2032-4923-81af-0a515de83811
		summarizeBy: none
		sourceColumn: rack_id

		annotation SummarizationSetBy = Automatic

	column server_type
		dataType: string
		isNullable: false
		lineageTag: d581b931-b35a-467e-a897-37ffb1c74e31
		summarizeBy: none
		sourceColumn: server_type

		annotation SummarizationSetBy = Automatic

	column cpu_cores
		dataType: int64
		isNullable: false
		lineageTag: 1e1bb53a-4e11-488a-858f-0b5a24bab1c9
		summarizeBy: none
		sourceColumn: cpu_cores

		annotation SummarizationSetBy = Automatic

	column memory_gb
		dataType: int64
		isNullable: false
		lineageTag: a71b6e06-d7cd-4f6a-9e0b-51a65b34c74c
		summarizeBy: none
		sourceColumn: memory_gb

		annotation SummarizationSetBy = Automatic

	column install_date
		dataType: dateTime
		isNullable: false
		formatString: Long Date
		lineageTag: a004a591-62fc-4434-acd6-7486f4fb9133
		summarizeBy: none
		sourceColumn: install_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column status
		dataType: string
		isNullable: false
		lineageTag: 3600d0b8-386f-4711-a203-187d06f42649
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	partition DimServer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/admin/Downloads/AI_Image_Classification_Final_Project_Import_Fixed/ai-data-center-intelligence/data/processed/servers.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"server_id", type text}, {"facility_id", type text}, {"rack_id", type text},
				        {"server_type", type text}, {"cpu_cores", Int64.Type}, {"memory_gb", Int64.Type},
				        {"install_date", type date}, {"status", type text}
				    })
				in
				    Typed

