table FactAlerts

	column alert_id
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: alert_id

		annotation SummarizationSetBy = Automatic

	column timestamp
		dataType: dateTime
		isNullable: false
		summarizeBy: none
		sourceColumn: timestamp

		annotation SummarizationSetBy = Automatic

	column facility_id
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: facility_id

		annotation SummarizationSetBy = Automatic

	column server_id
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: server_id

		annotation SummarizationSetBy = Automatic

	column component
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: component

		annotation SummarizationSetBy = Automatic

	column severity
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: severity

		annotation SummarizationSetBy = Automatic

	column alert_type
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: alert_type

		annotation SummarizationSetBy = Automatic

	column metric_name
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: metric_name

		annotation SummarizationSetBy = Automatic

	column observed_value
		dataType: double
		isNullable: false
		summarizeBy: none
		sourceColumn: observed_value

		annotation SummarizationSetBy = Automatic

	column threshold_value
		dataType: double
		isNullable: false
		summarizeBy: none
		sourceColumn: threshold_value

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column resolved_at
		dataType: dateTime
		isNullable: true
		summarizeBy: none
		sourceColumn: resolved_at

		annotation SummarizationSetBy = Automatic

	column alert_date
		dataType: dateTime
		isNullable: false
		summarizeBy: none
		sourceColumn: alert_date

		annotation SummarizationSetBy = Automatic

	partition FactAlerts = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/admin/Downloads/AI_Image_Classification_Final_Project_Import_Fixed/ai-data-center-intelligence/data/processed/alerts.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"alert_id", type text}, {"timestamp", type datetime}, {"facility_id", type text},
				        {"server_id", type text}, {"component", type text}, {"severity", type text},
				        {"alert_type", type text}, {"metric_name", type text}, {"observed_value", type number},
				        {"threshold_value", type number}, {"status", type text}, {"resolved_at", type datetime}
				    }),
				    AlertDate = Table.AddColumn(Typed, "alert_date", each Date.From([timestamp]), type date)
				in
				    AlertDate
