table FactServerMetrics
	lineageTag: a6fa7e76-6655-4475-87a3-a96ed2aff4ba

	column metric_id
		dataType: string
		isNullable: false
		lineageTag: bfdae84c-99bc-44b3-af02-18e669caecce
		summarizeBy: none
		sourceColumn: metric_id

		annotation SummarizationSetBy = Automatic

	column server_id
		dataType: string
		isNullable: false
		lineageTag: fa898739-b148-423c-9e08-9ada06b05429
		summarizeBy: none
		sourceColumn: server_id

		annotation SummarizationSetBy = Automatic

	column timestamp
		dataType: dateTime
		isNullable: false
		formatString: Long Date
		lineageTag: b213a2c0-9483-43ef-a3b2-c25a17019934
		summarizeBy: none
		sourceColumn: timestamp

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column cpu_utilization_pct
		dataType: double
		isNullable: false
		lineageTag: 0fd6d2d3-0f68-4c2d-aeef-110cb512aee7
		summarizeBy: none
		sourceColumn: cpu_utilization_pct

		annotation SummarizationSetBy = Automatic

	column memory_utilization_pct
		dataType: double
		isNullable: false
		lineageTag: b032f48c-f9ad-4c7f-962f-c73478413518
		summarizeBy: none
		sourceColumn: memory_utilization_pct

		annotation SummarizationSetBy = Automatic

	column disk_utilization_pct
		dataType: double
		isNullable: false
		lineageTag: ee8dfa73-1f35-4c9f-a25d-ea6ed83993af
		summarizeBy: none
		sourceColumn: disk_utilization_pct

		annotation SummarizationSetBy = Automatic

	column network_utilization_pct
		dataType: double
		isNullable: false
		lineageTag: b93ba534-ae5b-4e07-a70a-89bf7f3d7ef7
		summarizeBy: none
		sourceColumn: network_utilization_pct

		annotation SummarizationSetBy = Automatic

	partition FactServerMetrics = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/admin/Downloads/AI_Image_Classification_Final_Project_Import_Fixed/ai-data-center-intelligence/data/processed/server_metrics.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"metric_id", type text}, {"server_id", type text}, {"timestamp", type date},
				        {"cpu_utilization_pct", type number}, {"memory_utilization_pct", type number},
				        {"disk_utilization_pct", type number}, {"network_utilization_pct", type number}
				    })
				in
				    Typed

