table FactCostCarbon
	lineageTag: 0abde329-1d7c-4639-a628-38611c0df52c

	column snapshot_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 217986d9-0a69-481c-8f19-69f045adaaf2
		summarizeBy: none
		sourceColumn: snapshot_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		lineageTag: 1d03fc08-4066-4e39-a5b7-f43bf890cec2
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column month_label
		dataType: string
		lineageTag: c1a109e9-7cd1-48c2-b914-feed52d4beab
		summarizeBy: none
		sourceColumn: month_label

		annotation SummarizationSetBy = Automatic

	column facility_id
		dataType: string
		lineageTag: 3bdc8219-c9e1-417a-9f2a-ed02f881518e
		summarizeBy: none
		sourceColumn: facility_id

		annotation SummarizationSetBy = Automatic

	column facility_name
		dataType: string
		lineageTag: 74657efe-afb3-429e-ba0a-c4d0fbe7a47f
		summarizeBy: none
		sourceColumn: facility_name

		annotation SummarizationSetBy = Automatic

	column observation_days
		dataType: int64
		lineageTag: f39cf023-b074-408a-acb0-f6a22687add7
		summarizeBy: none
		sourceColumn: observation_days

		annotation SummarizationSetBy = Automatic

	column modeled_energy_kwh
		dataType: double
		lineageTag: c23410ea-10e9-4837-9570-3372c0639bf0
		summarizeBy: none
		sourceColumn: modeled_energy_kwh

		annotation SummarizationSetBy = Automatic

	column modeled_it_energy_kwh
		dataType: double
		lineageTag: 36c67419-0ec2-4844-ac66-4a12fbe11466
		summarizeBy: none
		sourceColumn: modeled_it_energy_kwh

		annotation SummarizationSetBy = Automatic

	column modeled_cooling_energy_kwh
		dataType: double
		lineageTag: 6d82a61c-ff70-4579-bda0-a24012c0a988
		summarizeBy: none
		sourceColumn: modeled_cooling_energy_kwh

		annotation SummarizationSetBy = Automatic

	column modeled_energy_cost_usd
		dataType: double
		lineageTag: d7849057-95e9-40e6-a6fa-6e5c696eb495
		summarizeBy: none
		sourceColumn: modeled_energy_cost_usd

		annotation SummarizationSetBy = Automatic

	column modeled_it_cost_usd
		dataType: double
		lineageTag: 0cb1951e-b94a-44c4-90cb-2ee693fed52a
		summarizeBy: none
		sourceColumn: modeled_it_cost_usd

		annotation SummarizationSetBy = Automatic

	column modeled_cooling_cost_usd
		dataType: double
		lineageTag: 1714105d-ec59-4b77-a172-2a42e7e711d9
		summarizeBy: none
		sourceColumn: modeled_cooling_cost_usd

		annotation SummarizationSetBy = Automatic

	column modeled_carbon_tonnes
		dataType: double
		lineageTag: aea22300-8f20-49f3-824c-889f526f924c
		summarizeBy: none
		sourceColumn: modeled_carbon_tonnes

		annotation SummarizationSetBy = Automatic

	column modeled_it_carbon_tonnes
		dataType: double
		lineageTag: e1c931a7-8ecd-485e-aa19-9fccaab6876c
		summarizeBy: none
		sourceColumn: modeled_it_carbon_tonnes

		annotation SummarizationSetBy = Automatic

	column modeled_cooling_carbon_tonnes
		dataType: double
		lineageTag: b3e2fa6d-5a5e-427c-af21-151f20590104
		summarizeBy: none
		sourceColumn: modeled_cooling_carbon_tonnes

		annotation SummarizationSetBy = Automatic

	column average_pue
		dataType: double
		lineageTag: eea363ff-bb1c-4696-9313-ec7baf6388d0
		summarizeBy: none
		sourceColumn: average_pue

		annotation SummarizationSetBy = Automatic

	column price_per_kwh
		dataType: double
		lineageTag: 911719c1-866a-4537-b4e7-6d2c3fe8e428
		summarizeBy: none
		sourceColumn: price_per_kwh

		annotation SummarizationSetBy = Automatic

	column grams_co2e_per_kwh
		dataType: double
		lineageTag: 2cd6b37e-2170-4a02-9499-e21b36ff05f2
		summarizeBy: none
		sourceColumn: grams_co2e_per_kwh

		annotation SummarizationSetBy = Automatic

	column efficiency_opportunity_score
		dataType: double
		lineageTag: fd4a0ccf-9605-4fbb-ba92-05dec29cf769
		summarizeBy: none
		sourceColumn: efficiency_opportunity_score

		annotation SummarizationSetBy = Automatic

	column currency
		dataType: string
		lineageTag: 3d6ca4c3-d024-49c4-b15d-1ecf81cddace
		summarizeBy: none
		sourceColumn: currency

		annotation SummarizationSetBy = Automatic

	column pricing_basis
		dataType: string
		lineageTag: b21869c2-da3f-49f9-adba-83af1953329c
		summarizeBy: none
		sourceColumn: pricing_basis

		annotation SummarizationSetBy = Automatic

	column price_source
		dataType: string
		lineageTag: 880b5763-d357-4e2d-a87b-ea838c442acc
		summarizeBy: none
		sourceColumn: price_source

		annotation SummarizationSetBy = Automatic

	column carbon_methodology
		dataType: string
		lineageTag: efe6fdce-cd91-4a37-85e1-bde12ff00fb1
		summarizeBy: none
		sourceColumn: carbon_methodology

		annotation SummarizationSetBy = Automatic

	column carbon_source
		dataType: string
		lineageTag: aed3a861-9f37-49a7-80a4-7885c351eb83
		summarizeBy: none
		sourceColumn: carbon_source

		annotation SummarizationSetBy = Automatic

	column assumptions_are_synthetic
		dataType: boolean
		lineageTag: 7300047a-2152-4337-80b9-1a5e8113159d
		summarizeBy: none
		sourceColumn: assumptions_are_synthetic

		annotation SummarizationSetBy = Automatic

	column snapshot_version
		dataType: string
		lineageTag: d75e7090-f8d8-45a5-bb25-65e251f74f58
		summarizeBy: none
		sourceColumn: snapshot_version

		annotation SummarizationSetBy = Automatic

	column source_period
		dataType: string
		lineageTag: bfcdda83-327b-46cd-93be-f22d9c446195
		summarizeBy: none
		sourceColumn: source_period

		annotation SummarizationSetBy = Automatic

	partition FactCostCarbon = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/admin/Downloads/AI_Image_Classification_Final_Project_Import_Fixed/ai-data-center-intelligence/data/processed/powerbi_cost_carbon_snapshot.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"snapshot_date", type date}, {"year", Int64.Type}, {"month_label", type text},
				        {"facility_id", type text}, {"facility_name", type text}, {"observation_days", Int64.Type},
				        {"modeled_energy_kwh", type number}, {"modeled_it_energy_kwh", type number},
				        {"modeled_cooling_energy_kwh", type number}, {"modeled_energy_cost_usd", type number},
				        {"modeled_it_cost_usd", type number}, {"modeled_cooling_cost_usd", type number},
				        {"modeled_carbon_tonnes", type number}, {"modeled_it_carbon_tonnes", type number},
				        {"modeled_cooling_carbon_tonnes", type number}, {"average_pue", type number},
				        {"price_per_kwh", type number}, {"grams_co2e_per_kwh", type number},
				        {"efficiency_opportunity_score", type number}, {"currency", type text},
				        {"pricing_basis", type text}, {"price_source", type text},
				        {"carbon_methodology", type text}, {"carbon_source", type text},
				        {"assumptions_are_synthetic", type logical}, {"snapshot_version", type text},
				        {"source_period", type text}
				    })
				in
				    Typed

