table FactServerRisk
	lineageTag: 0e33e664-ba7e-451d-a2cb-c9faa939fcf6

	column risk_id
		dataType: string
		isNullable: false
		lineageTag: db5d5f79-c377-4c0e-b9c8-25e15cacff0a
		summarizeBy: none
		sourceColumn: risk_id

		annotation SummarizationSetBy = Automatic

	column score_date
		dataType: dateTime
		isNullable: false
		formatString: Long Date
		lineageTag: 5f0acd46-9267-4151-9bee-dc5d746f421b
		summarizeBy: none
		sourceColumn: score_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column forecast_horizon_days
		dataType: int64
		isNullable: false
		lineageTag: 7f49b345-af6f-4bdd-a0b6-74b1f817e952
		summarizeBy: none
		sourceColumn: forecast_horizon_days

		annotation SummarizationSetBy = Automatic

	column server_id
		dataType: string
		isNullable: false
		lineageTag: c96d3366-8267-435e-8a7d-4548c30fb70a
		summarizeBy: none
		sourceColumn: server_id

		annotation SummarizationSetBy = Automatic

	column facility_id
		dataType: string
		isNullable: false
		lineageTag: a4119096-6877-4704-a57d-ae8d871bb308
		summarizeBy: none
		sourceColumn: facility_id

		annotation SummarizationSetBy = Automatic

	column risk_score
		dataType: double
		isNullable: false
		lineageTag: c1f17517-c163-4316-b4ab-f7d4207e3448
		summarizeBy: none
		sourceColumn: risk_score

		annotation SummarizationSetBy = Automatic

	column risk_level
		dataType: string
		isNullable: false
		lineageTag: 0bcf70e8-2b44-4954-8ece-ed9830b7bcfd
		summarizeBy: none
		sourceColumn: risk_level

		annotation SummarizationSetBy = Automatic

	column hardware_error_count
		dataType: int64
		isNullable: false
		lineageTag: 2a6d8129-ca71-41d3-ada7-9fc40b744e72
		summarizeBy: none
		sourceColumn: hardware_error_count

		annotation SummarizationSetBy = Automatic

	column service_impact_count
		dataType: int64
		isNullable: false
		lineageTag: 063af686-7898-416b-aacf-e398c80b8b22
		summarizeBy: none
		sourceColumn: service_impact_count

		annotation SummarizationSetBy = Automatic

	column thermal_signal_count
		dataType: int64
		isNullable: false
		lineageTag: 369176ed-2f65-4efd-9085-99872f37bf92
		summarizeBy: none
		sourceColumn: thermal_signal_count

		annotation SummarizationSetBy = Automatic

	column incident_count_365d
		dataType: int64
		isNullable: false
		lineageTag: 9456010d-9a72-4246-a399-29b128e89025
		summarizeBy: none
		sourceColumn: incident_count_365d

		annotation SummarizationSetBy = Automatic

	column incident_severity_points
		dataType: int64
		isNullable: false
		lineageTag: c1ae6fa3-7dfa-4faf-a580-5af03a981613
		summarizeBy: none
		sourceColumn: incident_severity_points

		annotation SummarizationSetBy = Automatic

	column maintenance_count_365d
		dataType: int64
		isNullable: false
		lineageTag: 014b94dd-7b14-49da-bce6-ce7b04755cda
		summarizeBy: none
		sourceColumn: maintenance_count_365d

		annotation SummarizationSetBy = Automatic

	column avg_cpu_30d
		dataType: double
		isNullable: false
		lineageTag: 54d7ee0d-8b31-406d-bc10-59f413b1f829
		summarizeBy: none
		sourceColumn: avg_cpu_30d

		annotation SummarizationSetBy = Automatic

	column avg_memory_30d
		dataType: double
		isNullable: false
		lineageTag: 579268db-009b-4bfb-ad6b-6190181ef320
		summarizeBy: none
		sourceColumn: avg_memory_30d

		annotation SummarizationSetBy = Automatic

	column avg_disk_30d
		dataType: double
		isNullable: false
		lineageTag: ea2e40ef-4612-4200-92b7-d857edb48140
		summarizeBy: none
		sourceColumn: avg_disk_30d

		annotation SummarizationSetBy = Automatic

	column asset_age_years
		dataType: double
		isNullable: false
		lineageTag: dbac04bc-6c9d-4ee8-9f56-6f55e727fe6e
		summarizeBy: none
		sourceColumn: asset_age_years

		annotation SummarizationSetBy = Automatic

	column primary_signal
		dataType: string
		isNullable: false
		lineageTag: 4cd5c85c-bb5a-4691-809b-fde506f76913
		summarizeBy: none
		sourceColumn: primary_signal

		annotation SummarizationSetBy = Automatic

	column recommendation
		dataType: string
		isNullable: false
		lineageTag: 3c689e7d-c233-4417-bde5-09cf7c2a278c
		summarizeBy: none
		sourceColumn: recommendation

		annotation SummarizationSetBy = Automatic

	column signal_summary_json
		dataType: string
		isNullable: false
		lineageTag: 94c2aa65-a138-485d-92d4-c7198fbc86fc
		summarizeBy: none
		sourceColumn: signal_summary_json

		annotation SummarizationSetBy = Automatic

	column lookback_days
		dataType: int64
		isNullable: false
		lineageTag: cfaa7ea7-f9cf-442a-aed5-da3e6e1680a3
		summarizeBy: none
		sourceColumn: lookback_days

		annotation SummarizationSetBy = Automatic

	column method_version
		dataType: string
		isNullable: false
		lineageTag: e5e7dd25-6db8-41f0-838c-bc3d54c7c132
		summarizeBy: none
		sourceColumn: method_version

		annotation SummarizationSetBy = Automatic

	partition FactServerRisk = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/admin/Downloads/AI_Image_Classification_Final_Project_Import_Fixed/ai-data-center-intelligence/data/processed/server_failure_risk.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"risk_id", type text}, {"score_date", type date}, {"forecast_horizon_days", Int64.Type},
				        {"server_id", type text}, {"facility_id", type text}, {"risk_score", type number},
				        {"risk_level", type text}, {"hardware_error_count", Int64.Type}, {"service_impact_count", Int64.Type},
				        {"thermal_signal_count", Int64.Type}, {"incident_count_365d", Int64.Type},
				        {"incident_severity_points", Int64.Type}, {"maintenance_count_365d", Int64.Type},
				        {"avg_cpu_30d", type number}, {"avg_memory_30d", type number}, {"avg_disk_30d", type number},
				        {"asset_age_years", type number}, {"primary_signal", type text}, {"recommendation", type text},
				        {"signal_summary_json", type text}, {"lookback_days", Int64.Type}, {"method_version", type text}
				    })
				in
				    Typed

