table FactSystemLogs
	lineageTag: f22f9aee-3425-42dc-9788-663364efd937

	column log_id
		dataType: string
		isNullable: false
		lineageTag: 9e375349-c3fc-49a6-b1ac-fffd06e00eed
		summarizeBy: none
		sourceColumn: log_id

		annotation SummarizationSetBy = Automatic

	column timestamp
		dataType: dateTime
		isNullable: false
		lineageTag: d64dc5f0-891f-4d2c-b873-a9d3313392c4
		summarizeBy: none
		sourceColumn: timestamp

		annotation SummarizationSetBy = Automatic

	column facility_id
		dataType: string
		isNullable: false
		lineageTag: a3caa362-4f3a-47be-901a-44b8efe6c6a1
		summarizeBy: none
		sourceColumn: facility_id

		annotation SummarizationSetBy = Automatic

	column server_id
		dataType: string
		isNullable: false
		lineageTag: 449b451f-79d0-4d54-b763-0285aed25576
		summarizeBy: none
		sourceColumn: server_id

		annotation SummarizationSetBy = Automatic

	column rack_id
		dataType: string
		isNullable: false
		lineageTag: 672d5a2a-fd08-4623-bfe1-7fdcf6da477e
		summarizeBy: none
		sourceColumn: rack_id

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		isNullable: false
		lineageTag: f950b579-0978-4e83-a98f-3ad0f50f38da
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column component
		dataType: string
		isNullable: false
		lineageTag: 74a1d891-ddfb-493f-9468-b3dde568d362
		summarizeBy: none
		sourceColumn: component

		annotation SummarizationSetBy = Automatic

	column log_level
		dataType: string
		isNullable: false
		lineageTag: 9748260a-dff2-494d-b38d-4685e859c3ba
		summarizeBy: none
		sourceColumn: log_level

		annotation SummarizationSetBy = Automatic

	column event_code
		dataType: string
		isNullable: false
		lineageTag: 0df0e593-ae3d-4cc8-9ee6-2f0e1774075e
		summarizeBy: none
		sourceColumn: event_code

		annotation SummarizationSetBy = Automatic

	column message
		dataType: string
		isNullable: false
		lineageTag: 2f8464fb-cd0e-4c1d-a65c-491d1b7860f4
		summarizeBy: none
		sourceColumn: message

		annotation SummarizationSetBy = Automatic

	column log_date
		dataType: dateTime
		isNullable: false
		formatString: Long Date
		lineageTag: a2493bbe-8cf1-4f22-8280-aa9674dbbcf2
		summarizeBy: none
		sourceColumn: log_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition FactSystemLogs = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/admin/Downloads/AI_Image_Classification_Final_Project_Import_Fixed/ai-data-center-intelligence/data/processed/system_logs.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"log_id", type text}, {"timestamp", type datetime}, {"facility_id", type text},
				        {"server_id", type text}, {"rack_id", type text}, {"source", type text},
				        {"component", type text}, {"log_level", type text}, {"event_code", type text}, {"message", type text}
				    }),
				    LogDate = Table.AddColumn(Typed, "log_date", each Date.From([timestamp]), type date)
				in
				    LogDate

