table FactNetworkMetrics
	lineageTag: 49346ec5-31eb-4ca5-a1b0-f7c0661d24c8

	column metric_id
		dataType: string
		isNullable: false
		lineageTag: 2d16e2ce-1cfc-45b7-9774-6ec7a7905c83
		summarizeBy: none
		sourceColumn: metric_id

		annotation SummarizationSetBy = Automatic

	column facility_id
		dataType: string
		isNullable: false
		lineageTag: c0ea16f1-5dcb-4aa5-bc77-911d3600aef6
		summarizeBy: none
		sourceColumn: facility_id

		annotation SummarizationSetBy = Automatic

	column timestamp
		dataType: dateTime
		isNullable: false
		formatString: Long Date
		lineageTag: a8233c31-e16c-4f5e-a9a3-763890cf4a23
		summarizeBy: none
		sourceColumn: timestamp

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column bandwidth_utilization_pct
		dataType: double
		isNullable: false
		lineageTag: 98e24f47-f51e-477a-ba89-302c6a7271d0
		summarizeBy: none
		sourceColumn: bandwidth_utilization_pct

		annotation SummarizationSetBy = Automatic

	column latency_ms
		dataType: double
		isNullable: false
		lineageTag: 6700a58e-c467-40b0-8b14-53c74eb6866f
		summarizeBy: none
		sourceColumn: latency_ms

		annotation SummarizationSetBy = Automatic

	column packet_loss_pct
		dataType: double
		isNullable: false
		lineageTag: fb513001-6be6-4a00-a8ff-9556d29a137c
		summarizeBy: none
		sourceColumn: packet_loss_pct

		annotation SummarizationSetBy = Automatic

	column throughput_mbps
		dataType: double
		isNullable: false
		lineageTag: bb4e37d7-5a68-444f-a99f-2fc79a18a999
		summarizeBy: none
		sourceColumn: throughput_mbps

		annotation SummarizationSetBy = Automatic

	column network_availability_pct
		dataType: double
		isNullable: false
		lineageTag: 30a18458-b414-4c3a-9af2-1f9ad89fd149
		summarizeBy: none
		sourceColumn: network_availability_pct

		annotation SummarizationSetBy = Automatic

	partition FactNetworkMetrics = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/admin/Downloads/AI_Image_Classification_Final_Project_Import_Fixed/ai-data-center-intelligence/data/processed/network_metrics.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"metric_id", type text}, {"facility_id", type text}, {"timestamp", type date},
				        {"bandwidth_utilization_pct", type number}, {"latency_ms", type number},
				        {"packet_loss_pct", type number}, {"throughput_mbps", type number},
				        {"network_availability_pct", type number}
				    })
				in
				    Typed

