table FactAnomalies

	column anomaly_id
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: anomaly_id

		annotation SummarizationSetBy = Automatic

	column timestamp
		dataType: dateTime
		isNullable: false
		summarizeBy: none
		sourceColumn: timestamp

		annotation SummarizationSetBy = Automatic

	column facility_id
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: facility_id

		annotation SummarizationSetBy = Automatic

	column metric_name
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: metric_name

		annotation SummarizationSetBy = Automatic

	column observed_value
		dataType: double
		isNullable: false
		summarizeBy: none
		sourceColumn: observed_value

		annotation SummarizationSetBy = Automatic

	column expected_value
		dataType: double
		isNullable: false
		summarizeBy: none
		sourceColumn: expected_value

		annotation SummarizationSetBy = Automatic

	column lower_bound
		dataType: double
		isNullable: false
		summarizeBy: none
		sourceColumn: lower_bound

		annotation SummarizationSetBy = Automatic

	column upper_bound
		dataType: double
		isNullable: false
		summarizeBy: none
		sourceColumn: upper_bound

		annotation SummarizationSetBy = Automatic

	column deviation_pct
		dataType: double
		isNullable: false
		summarizeBy: none
		sourceColumn: deviation_pct

		annotation SummarizationSetBy = Automatic

	column direction
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: direction

		annotation SummarizationSetBy = Automatic

	column severity
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: severity

		annotation SummarizationSetBy = Automatic

	column anomaly_score
		dataType: double
		isNullable: false
		summarizeBy: none
		sourceColumn: anomaly_score

		annotation SummarizationSetBy = Automatic

	column method
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: method

		annotation SummarizationSetBy = Automatic

	column source_table
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: source_table

		annotation SummarizationSetBy = Automatic

	column source_grain
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: source_grain

		annotation SummarizationSetBy = Automatic

	column source_record_count
		dataType: int64
		isNullable: false
		summarizeBy: none
		sourceColumn: source_record_count

		annotation SummarizationSetBy = Automatic

	partition FactAnomalies = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/admin/Downloads/AI_Image_Classification_Final_Project_Import_Fixed/ai-data-center-intelligence/data/processed/detected_anomalies.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"anomaly_id", type text}, {"timestamp", type date}, {"facility_id", type text},
				        {"metric_name", type text}, {"observed_value", type number}, {"expected_value", type number},
				        {"lower_bound", type number}, {"upper_bound", type number}, {"deviation_pct", type number},
				        {"direction", type text}, {"severity", type text}, {"anomaly_score", type number},
				        {"method", type text}, {"source_table", type text}, {"source_grain", type text},
				        {"source_record_count", Int64.Type}
				    })
				in
				    Typed
