table FactMaintenanceActions
	lineageTag: 89ea5c34-8e77-4ad5-9f41-247af65bab36

	column action_id
		dataType: string
		isNullable: false
		lineageTag: fd0650ee-f706-40ee-9ec7-f2a0defeb00e
		summarizeBy: none
		sourceColumn: action_id

		annotation SummarizationSetBy = Automatic

	column incident_id
		dataType: string
		isNullable: false
		lineageTag: 3d183edd-3f6e-46bc-81b5-c1827f13466f
		summarizeBy: none
		sourceColumn: incident_id

		annotation SummarizationSetBy = Automatic

	column facility_id
		dataType: string
		isNullable: false
		lineageTag: fb08d6d3-92d2-436e-a4ba-e62d4bb4a90d
		summarizeBy: none
		sourceColumn: facility_id

		annotation SummarizationSetBy = Automatic

	column server_id
		dataType: string
		isNullable: false
		lineageTag: ced57b39-84e2-42b5-9d47-f508d58f12e7
		summarizeBy: none
		sourceColumn: server_id

		annotation SummarizationSetBy = Automatic

	column timestamp
		dataType: dateTime
		isNullable: false
		lineageTag: 7a8fa0ea-c0d1-4f4a-9571-b668ea122607
		summarizeBy: none
		sourceColumn: timestamp

		annotation SummarizationSetBy = Automatic

	column action_type
		dataType: string
		isNullable: false
		lineageTag: 1253e6f0-adc4-45b2-9f3b-44af17ef5d3a
		summarizeBy: none
		sourceColumn: action_type

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		isNullable: false
		lineageTag: f0069b4e-585a-4fea-8ba6-632f8b702439
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column result
		dataType: string
		isNullable: false
		lineageTag: 34382b73-a44b-491e-aae6-6b8cfc591fcf
		summarizeBy: none
		sourceColumn: result

		annotation SummarizationSetBy = Automatic

	column performed_by_role
		dataType: string
		isNullable: false
		lineageTag: b121bc41-abf7-4644-bee1-170c84b93f63
		summarizeBy: none
		sourceColumn: performed_by_role

		annotation SummarizationSetBy = Automatic

	column action_date
		dataType: dateTime
		isNullable: false
		formatString: Long Date
		lineageTag: d353a559-d49e-41ec-96c1-b56bf0962083
		summarizeBy: none
		sourceColumn: action_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition FactMaintenanceActions = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/admin/Downloads/AI_Image_Classification_Final_Project_Import_Fixed/ai-data-center-intelligence/data/processed/maintenance_actions.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"action_id", type text}, {"incident_id", type text}, {"facility_id", type text},
				        {"server_id", type text}, {"timestamp", type datetime}, {"action_type", type text},
				        {"description", type text}, {"result", type text}, {"performed_by_role", type text}
				    }),
				    ActionDate = Table.AddColumn(Typed, "action_date", each Date.From([timestamp]), type date)
				in
				    ActionDate

