table FactLiveOperationsSnapshot
	lineageTag: 159bc8ed-cec6-46e7-b351-f9213a945268

	column simulation_session_id
		dataType: string
		lineageTag: 54ccd371-1510-44f2-a5e5-7ae133aa1fcd
		summarizeBy: none
		sourceColumn: simulation_session_id

		annotation SummarizationSetBy = Automatic

	column scenario_name
		dataType: string
		lineageTag: f503b009-12f9-404f-8f89-f93d4165745d
		summarizeBy: none
		sourceColumn: scenario_name

		annotation SummarizationSetBy = Automatic

	column session_status
		dataType: string
		lineageTag: fe2a2295-9bdd-4aa7-9012-c068d1a2bd00
		summarizeBy: none
		sourceColumn: session_status

		annotation SummarizationSetBy = Automatic

	column snapshot_timestamp
		dataType: dateTime
		lineageTag: ccec1609-de8e-40c3-8d11-1fe215b0dfcc
		summarizeBy: none
		sourceColumn: snapshot_timestamp

		annotation SummarizationSetBy = Automatic

	column facility_id
		dataType: string
		lineageTag: ddec05b7-006d-46aa-91b0-6995316f836a
		summarizeBy: none
		sourceColumn: facility_id

		annotation SummarizationSetBy = Automatic

	column facility_name
		dataType: string
		lineageTag: 7dbdb580-fe21-4e01-9c71-acd347256f21
		summarizeBy: none
		sourceColumn: facility_name

		annotation SummarizationSetBy = Automatic

	column health_score
		dataType: double
		lineageTag: 702d1612-6a60-4d94-86dd-492f55e64456
		summarizeBy: none
		sourceColumn: health_score

		annotation SummarizationSetBy = Automatic

	column energy_efficiency_score
		dataType: double
		lineageTag: 4588f995-4073-4020-a25e-341d15fbcc7a
		summarizeBy: none
		sourceColumn: energy_efficiency_score

		annotation SummarizationSetBy = Automatic

	column reliability_score
		dataType: double
		lineageTag: 01d40b97-3083-4182-b298-b0eedb1d4211
		summarizeBy: none
		sourceColumn: reliability_score

		annotation SummarizationSetBy = Automatic

	column network_health_score
		dataType: double
		lineageTag: 8f364623-13ea-408b-be02-de4b5aa63eed
		summarizeBy: none
		sourceColumn: network_health_score

		annotation SummarizationSetBy = Automatic

	column infrastructure_score
		dataType: double
		lineageTag: 43d2575c-a0a8-419c-b108-8a75eb995864
		summarizeBy: none
		sourceColumn: infrastructure_score

		annotation SummarizationSetBy = Automatic

	column alert_score
		dataType: double
		lineageTag: 2a7fa8e0-4208-447d-8edb-eeb390e8c34b
		summarizeBy: none
		sourceColumn: alert_score

		annotation SummarizationSetBy = Automatic

	column anomaly_score
		dataType: double
		lineageTag: 57a6e8b1-9aed-40bd-827a-2a315a9ef7e1
		summarizeBy: none
		sourceColumn: anomaly_score

		annotation SummarizationSetBy = Automatic

	column active_alert_count
		dataType: int64
		lineageTag: d25c851f-5e48-4a02-afdc-40ee312a8e57
		summarizeBy: none
		sourceColumn: active_alert_count

		annotation SummarizationSetBy = Automatic

	column active_anomaly_count
		dataType: int64
		lineageTag: 7854bcd9-1314-426b-b91e-e1b974fb7976
		summarizeBy: none
		sourceColumn: active_anomaly_count

		annotation SummarizationSetBy = Automatic

	column data_completeness_pct
		dataType: double
		lineageTag: 613675b0-5289-44d6-b997-deee092edaef
		summarizeBy: none
		sourceColumn: data_completeness_pct

		annotation SummarizationSetBy = Automatic

	column method_version
		dataType: string
		lineageTag: ac2d9f5f-aa67-4705-a387-d87daf3f49c5
		summarizeBy: none
		sourceColumn: method_version

		annotation SummarizationSetBy = Automatic

	column is_synthetic
		dataType: boolean
		lineageTag: ab5bec69-bee5-4654-9e43-315f850eea55
		summarizeBy: none
		sourceColumn: is_synthetic

		annotation SummarizationSetBy = Automatic

	column snapshot_version
		dataType: string
		lineageTag: f28e23be-3135-4c51-9735-c92e80d591a2
		summarizeBy: none
		sourceColumn: snapshot_version

		annotation SummarizationSetBy = Automatic

	partition FactLiveOperationsSnapshot = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/admin/Downloads/AI_Image_Classification_Final_Project_Import_Fixed/ai-data-center-intelligence/data/processed/powerbi_live_operations_snapshot.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"simulation_session_id", type text}, {"scenario_name", type text},
				        {"session_status", type text}, {"snapshot_timestamp", type datetime},
				        {"facility_id", type text}, {"facility_name", type text}, {"health_score", type number},
				        {"energy_efficiency_score", type number}, {"reliability_score", type number},
				        {"network_health_score", type number}, {"infrastructure_score", type number},
				        {"alert_score", type number}, {"anomaly_score", type number},
				        {"active_alert_count", Int64.Type}, {"active_anomaly_count", Int64.Type},
				        {"data_completeness_pct", type number}, {"method_version", type text},
				        {"is_synthetic", type logical}, {"snapshot_version", type text}
				    })
				in
				    Typed

