table FactAlerts
	lineageTag: ae9463cd-5d1c-410a-a4f3-00c00fc6fa53

	column alert_id
		dataType: string
		isNullable: false
		lineageTag: 696360d2-3a0e-4163-b57d-43dc71ba0a05
		summarizeBy: none
		sourceColumn: alert_id

		annotation SummarizationSetBy = Automatic

	column timestamp
		dataType: dateTime
		isNullable: false
		lineageTag: 3ad4cf6b-f1f5-45d9-9ec0-14cfcc806a4c
		summarizeBy: none
		sourceColumn: timestamp

		annotation SummarizationSetBy = Automatic

	column facility_id
		dataType: string
		isNullable: false
		lineageTag: bea48872-836b-41b7-b6dd-1c57d1bd5321
		summarizeBy: none
		sourceColumn: facility_id

		annotation SummarizationSetBy = Automatic

	column server_id
		dataType: string
		isNullable: false
		lineageTag: 1d6a5bea-fa88-41ff-8ca2-cb091a68e31c
		summarizeBy: none
		sourceColumn: server_id

		annotation SummarizationSetBy = Automatic

	column component
		dataType: string
		isNullable: false
		lineageTag: 94c47753-c464-4d7e-b445-3485f2a09b8f
		summarizeBy: none
		sourceColumn: component

		annotation SummarizationSetBy = Automatic

	column severity
		dataType: string
		isNullable: false
		lineageTag: d59bb0b5-6267-4505-a350-6efe4bb44069
		summarizeBy: none
		sourceColumn: severity

		annotation SummarizationSetBy = Automatic

	column alert_type
		dataType: string
		isNullable: false
		lineageTag: fffa0673-600e-4cc7-92fd-28d58347bbed
		summarizeBy: none
		sourceColumn: alert_type

		annotation SummarizationSetBy = Automatic

	column metric_name
		dataType: string
		isNullable: false
		lineageTag: 5030f447-7f79-4d52-afd5-30d511a35ec1
		summarizeBy: none
		sourceColumn: metric_name

		annotation SummarizationSetBy = Automatic

	column observed_value
		dataType: double
		isNullable: false
		lineageTag: 4ea2603e-f24e-4363-ad66-adcfa142a450
		summarizeBy: none
		sourceColumn: observed_value

		annotation SummarizationSetBy = Automatic

	column threshold_value
		dataType: double
		isNullable: false
		lineageTag: 92c16710-7f95-4e40-844d-975f29f8b98b
		summarizeBy: none
		sourceColumn: threshold_value

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		isNullable: false
		lineageTag: 9b2fa6c8-6fcd-429b-9850-821fced60721
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column resolved_at
		dataType: dateTime
		lineageTag: 980c6e6f-2183-43c4-856f-c7b54faa5e7b
		summarizeBy: none
		sourceColumn: resolved_at

		annotation SummarizationSetBy = Automatic

	column alert_date
		dataType: dateTime
		isNullable: false
		formatString: Long Date
		lineageTag: e4fce142-2743-467b-b9a1-412c247eecae
		summarizeBy: none
		sourceColumn: alert_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition FactAlerts = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/admin/Downloads/AI_Image_Classification_Final_Project_Import_Fixed/ai-data-center-intelligence/data/processed/alerts.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"alert_id", type text}, {"timestamp", type datetime}, {"facility_id", type text},
				        {"server_id", type text}, {"component", type text}, {"severity", type text},
				        {"alert_type", type text}, {"metric_name", type text}, {"observed_value", type number},
				        {"threshold_value", type number}, {"status", type text}, {"resolved_at", type datetime}
				    }),
				    AlertDate = Table.AddColumn(Typed, "alert_date", each Date.From([timestamp]), type date)
				in
				    AlertDate

