table FactPowerMetrics
	lineageTag: be0ed90e-7985-4f5b-8032-8fd3195097e0

	column metric_id
		dataType: string
		isNullable: false
		lineageTag: 0fb7420f-d1c1-4c56-9d08-a318f587d66b
		summarizeBy: none
		sourceColumn: metric_id

		annotation SummarizationSetBy = Automatic

	column facility_id
		dataType: string
		isNullable: false
		lineageTag: dcc3050d-a365-4995-9616-dea0915c5ee7
		summarizeBy: none
		sourceColumn: facility_id

		annotation SummarizationSetBy = Automatic

	column timestamp
		dataType: dateTime
		isNullable: false
		formatString: Long Date
		lineageTag: 08c2a94f-a5bf-4df1-93f4-78a939bb4180
		summarizeBy: none
		sourceColumn: timestamp

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column power_draw_kw
		dataType: double
		isNullable: false
		lineageTag: 806f48e0-d752-4c5d-86b1-0e717a7fe6e6
		summarizeBy: none
		sourceColumn: power_draw_kw

		annotation SummarizationSetBy = Automatic

	column it_load_kw
		dataType: double
		isNullable: false
		lineageTag: b426fd68-7771-4362-8af1-0db863068d1a
		summarizeBy: none
		sourceColumn: it_load_kw

		annotation SummarizationSetBy = Automatic

	column cooling_power_kw
		dataType: double
		isNullable: false
		lineageTag: f3914aa8-9da0-41e3-95c6-c508d881e2fe
		summarizeBy: none
		sourceColumn: cooling_power_kw

		annotation SummarizationSetBy = Automatic

	column pue
		dataType: double
		isNullable: false
		lineageTag: 59124a36-f036-4559-8198-83193593fd89
		summarizeBy: none
		sourceColumn: pue

		annotation SummarizationSetBy = Automatic

	column cooling_cost
		dataType: double
		isNullable: false
		lineageTag: 19b17956-67c4-4d9f-818e-b55aa350eed5
		summarizeBy: none
		sourceColumn: cooling_cost

		annotation SummarizationSetBy = Automatic

	partition FactPowerMetrics = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/admin/Downloads/AI_Image_Classification_Final_Project_Import_Fixed/ai-data-center-intelligence/data/processed/power_metrics.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"metric_id", type text}, {"facility_id", type text}, {"timestamp", type date},
				        {"power_draw_kw", type number}, {"it_load_kw", type number},
				        {"cooling_power_kw", type number}, {"pue", type number}, {"cooling_cost", type number}
				    })
				in
				    Typed

