table FactServerMetrics

	column metric_id
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: metric_id

		annotation SummarizationSetBy = Automatic

	column server_id
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: server_id

		annotation SummarizationSetBy = Automatic

	column timestamp
		dataType: dateTime
		isNullable: false
		summarizeBy: none
		sourceColumn: timestamp

		annotation SummarizationSetBy = Automatic

	column cpu_utilization_pct
		dataType: double
		isNullable: false
		summarizeBy: none
		sourceColumn: cpu_utilization_pct

		annotation SummarizationSetBy = Automatic

	column memory_utilization_pct
		dataType: double
		isNullable: false
		summarizeBy: none
		sourceColumn: memory_utilization_pct

		annotation SummarizationSetBy = Automatic

	column disk_utilization_pct
		dataType: double
		isNullable: false
		summarizeBy: none
		sourceColumn: disk_utilization_pct

		annotation SummarizationSetBy = Automatic

	column network_utilization_pct
		dataType: double
		isNullable: false
		summarizeBy: none
		sourceColumn: network_utilization_pct

		annotation SummarizationSetBy = Automatic

	partition FactServerMetrics = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/admin/Downloads/AI_Image_Classification_Final_Project_Import_Fixed/ai-data-center-intelligence/data/processed/server_metrics.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"metric_id", type text}, {"server_id", type text}, {"timestamp", type date},
				        {"cpu_utilization_pct", type number}, {"memory_utilization_pct", type number},
				        {"disk_utilization_pct", type number}, {"network_utilization_pct", type number}
				    })
				in
				    Typed
