table FactServerRisk

	column risk_id
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: risk_id

		annotation SummarizationSetBy = Automatic

	column score_date
		dataType: dateTime
		isNullable: false
		summarizeBy: none
		sourceColumn: score_date

		annotation SummarizationSetBy = Automatic

	column forecast_horizon_days
		dataType: int64
		isNullable: false
		summarizeBy: none
		sourceColumn: forecast_horizon_days

		annotation SummarizationSetBy = Automatic

	column server_id
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: server_id

		annotation SummarizationSetBy = Automatic

	column facility_id
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: facility_id

		annotation SummarizationSetBy = Automatic

	column risk_score
		dataType: double
		isNullable: false
		summarizeBy: none
		sourceColumn: risk_score

		annotation SummarizationSetBy = Automatic

	column risk_level
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: risk_level

		annotation SummarizationSetBy = Automatic

	column hardware_error_count
		dataType: int64
		isNullable: false
		summarizeBy: none
		sourceColumn: hardware_error_count

		annotation SummarizationSetBy = Automatic

	column service_impact_count
		dataType: int64
		isNullable: false
		summarizeBy: none
		sourceColumn: service_impact_count

		annotation SummarizationSetBy = Automatic

	column thermal_signal_count
		dataType: int64
		isNullable: false
		summarizeBy: none
		sourceColumn: thermal_signal_count

		annotation SummarizationSetBy = Automatic

	column incident_count_365d
		dataType: int64
		isNullable: false
		summarizeBy: none
		sourceColumn: incident_count_365d

		annotation SummarizationSetBy = Automatic

	column incident_severity_points
		dataType: int64
		isNullable: false
		summarizeBy: none
		sourceColumn: incident_severity_points

		annotation SummarizationSetBy = Automatic

	column maintenance_count_365d
		dataType: int64
		isNullable: false
		summarizeBy: none
		sourceColumn: maintenance_count_365d

		annotation SummarizationSetBy = Automatic

	column avg_cpu_30d
		dataType: double
		isNullable: false
		summarizeBy: none
		sourceColumn: avg_cpu_30d

		annotation SummarizationSetBy = Automatic

	column avg_memory_30d
		dataType: double
		isNullable: false
		summarizeBy: none
		sourceColumn: avg_memory_30d

		annotation SummarizationSetBy = Automatic

	column avg_disk_30d
		dataType: double
		isNullable: false
		summarizeBy: none
		sourceColumn: avg_disk_30d

		annotation SummarizationSetBy = Automatic

	column asset_age_years
		dataType: double
		isNullable: false
		summarizeBy: none
		sourceColumn: asset_age_years

		annotation SummarizationSetBy = Automatic

	column primary_signal
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: primary_signal

		annotation SummarizationSetBy = Automatic

	column recommendation
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: recommendation

		annotation SummarizationSetBy = Automatic

	column signal_summary_json
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: signal_summary_json

		annotation SummarizationSetBy = Automatic

	column lookback_days
		dataType: int64
		isNullable: false
		summarizeBy: none
		sourceColumn: lookback_days

		annotation SummarizationSetBy = Automatic

	column method_version
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: method_version

		annotation SummarizationSetBy = Automatic

	partition FactServerRisk = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/admin/Downloads/AI_Image_Classification_Final_Project_Import_Fixed/ai-data-center-intelligence/data/processed/server_failure_risk.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"risk_id", type text}, {"score_date", type date}, {"forecast_horizon_days", Int64.Type},
				        {"server_id", type text}, {"facility_id", type text}, {"risk_score", type number},
				        {"risk_level", type text}, {"hardware_error_count", Int64.Type}, {"service_impact_count", Int64.Type},
				        {"thermal_signal_count", Int64.Type}, {"incident_count_365d", Int64.Type},
				        {"incident_severity_points", Int64.Type}, {"maintenance_count_365d", Int64.Type},
				        {"avg_cpu_30d", type number}, {"avg_memory_30d", type number}, {"avg_disk_30d", type number},
				        {"asset_age_years", type number}, {"primary_signal", type text}, {"recommendation", type text},
				        {"signal_summary_json", type text}, {"lookback_days", Int64.Type}, {"method_version", type text}
				    })
				in
				    Typed
