table FactIncidents
	lineageTag: bfeb6263-bb43-445e-bf13-40b3048474cd

	column incident_id
		dataType: string
		isNullable: false
		lineageTag: 484bc524-325e-4480-88b7-c2146a643fc5
		summarizeBy: none
		sourceColumn: incident_id

		annotation SummarizationSetBy = Automatic

	column facility_id
		dataType: string
		isNullable: false
		lineageTag: 507261a2-27c8-4c34-8426-be9c1dc9dff0
		summarizeBy: none
		sourceColumn: facility_id

		annotation SummarizationSetBy = Automatic

	column server_id
		dataType: string
		isNullable: false
		lineageTag: 3b31abe2-ee60-4e79-883e-694a195491de
		summarizeBy: none
		sourceColumn: server_id

		annotation SummarizationSetBy = Automatic

	column start_time
		dataType: dateTime
		isNullable: false
		lineageTag: bf4b8adc-5698-4203-a8bc-4e7606de4343
		summarizeBy: none
		sourceColumn: start_time

		annotation SummarizationSetBy = Automatic

	column end_time
		dataType: dateTime
		isNullable: false
		lineageTag: 440a9732-0368-4251-a023-c559c3c5bad8
		summarizeBy: none
		sourceColumn: end_time

		annotation SummarizationSetBy = Automatic

	column downtime_minutes
		dataType: int64
		isNullable: false
		lineageTag: c4cb7fc2-e755-4a1e-b7fd-a4d434ffb2d0
		summarizeBy: none
		sourceColumn: downtime_minutes

		annotation SummarizationSetBy = Automatic

	column severity
		dataType: string
		isNullable: false
		lineageTag: 25bc286d-ae59-4e1d-9068-cfc14e0ce863
		summarizeBy: none
		sourceColumn: severity

		annotation SummarizationSetBy = Automatic

	column root_cause
		dataType: string
		isNullable: false
		lineageTag: d51d65cc-3fda-46e1-aeb6-fb8724cd2d49
		summarizeBy: none
		sourceColumn: root_cause

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		isNullable: false
		lineageTag: 15d30349-0f16-4f4c-8791-599eac5ade0f
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column incident_date
		dataType: dateTime
		isNullable: false
		formatString: Long Date
		lineageTag: 91535fec-fdb3-477e-ba28-8d64551055d5
		summarizeBy: none
		sourceColumn: incident_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition FactIncidents = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/admin/Downloads/AI_Image_Classification_Final_Project_Import_Fixed/ai-data-center-intelligence/data/processed/uptime_incidents.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"incident_id", type text}, {"facility_id", type text}, {"server_id", type text},
				        {"start_time", type datetime}, {"end_time", type datetime},
				        {"downtime_minutes", Int64.Type}, {"severity", type text},
				        {"root_cause", type text}, {"status", type text}
				    }),
				    IncidentDate = Table.AddColumn(Typed, "incident_date", each Date.From([start_time]), type date)
				in
				    IncidentDate

