table FactIncidentImpact
	lineageTag: 444ae96b-aa4e-49c1-bcac-60f4044504e5

	column incident_id
		dataType: string
		lineageTag: 974d421b-702c-4395-a5de-734e65af7c28
		summarizeBy: none
		sourceColumn: incident_id

		annotation SummarizationSetBy = Automatic

	column incident_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9ec0473e-55ff-43de-8107-22aa4e17e087
		summarizeBy: none
		sourceColumn: incident_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column facility_id
		dataType: string
		lineageTag: 819bacd6-4878-4d8c-a5af-85f48e3d6eb5
		summarizeBy: none
		sourceColumn: facility_id

		annotation SummarizationSetBy = Automatic

	column facility_name
		dataType: string
		lineageTag: 8bd27e28-7ca8-4315-9645-294fe69d7a96
		summarizeBy: none
		sourceColumn: facility_name

		annotation SummarizationSetBy = Automatic

	column server_id
		dataType: string
		lineageTag: c9b44d5c-1973-42e2-9920-baea3989aa5e
		summarizeBy: none
		sourceColumn: server_id

		annotation SummarizationSetBy = Automatic

	column severity
		dataType: string
		lineageTag: 3bc5ab68-39d2-4b26-a348-9ec8314ea157
		summarizeBy: none
		sourceColumn: severity

		annotation SummarizationSetBy = Automatic

	column root_cause
		dataType: string
		lineageTag: 49c571af-19dc-4797-a933-3286e751413b
		summarizeBy: none
		sourceColumn: root_cause

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: fdcd5cbf-6e3d-46d5-aeb4-0a490d4ff52a
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column downtime_minutes
		dataType: int64
		lineageTag: dc28045f-23fc-414f-b8d7-6fee6716e5af
		summarizeBy: none
		sourceColumn: downtime_minutes

		annotation SummarizationSetBy = Automatic

	column during_pue
		dataType: double
		lineageTag: 34da4078-01ef-4e36-b2a0-0c56431dd5ac
		summarizeBy: none
		sourceColumn: during_pue

		annotation SummarizationSetBy = Automatic

	column during_latency_ms
		dataType: double
		lineageTag: 60cc46b6-10cf-43d5-aa4e-59589f6aa35b
		summarizeBy: none
		sourceColumn: during_latency_ms

		annotation SummarizationSetBy = Automatic

	column during_packet_loss_pct
		dataType: double
		lineageTag: 47fc4f00-b4dd-45c8-bc5d-8e407771cd0c
		summarizeBy: none
		sourceColumn: during_packet_loss_pct

		annotation SummarizationSetBy = Automatic

	column during_network_availability_pct
		dataType: double
		lineageTag: 88ab14ea-1af8-4d19-bcb8-2df2c23118cd
		summarizeBy: none
		sourceColumn: during_network_availability_pct

		annotation SummarizationSetBy = Automatic

	column before_pue
		dataType: double
		lineageTag: 7ba67f77-7d80-470c-a6ea-ad1825674b00
		summarizeBy: none
		sourceColumn: before_pue

		annotation SummarizationSetBy = Automatic

	column after_pue
		dataType: double
		lineageTag: 8a16b3e7-bc0f-4c5c-9a0f-964aa1ff0bb8
		summarizeBy: none
		sourceColumn: after_pue

		annotation SummarizationSetBy = Automatic

	column before_latency_ms
		dataType: double
		lineageTag: 97158601-4549-41b6-8541-b52e7ae4cdd9
		summarizeBy: none
		sourceColumn: before_latency_ms

		annotation SummarizationSetBy = Automatic

	column after_latency_ms
		dataType: double
		lineageTag: 46f0f863-e2c9-44d0-9e2b-8a8e0c64ac41
		summarizeBy: none
		sourceColumn: after_latency_ms

		annotation SummarizationSetBy = Automatic

	column before_packet_loss_pct
		dataType: double
		lineageTag: bd1fd944-46b2-441c-824f-6e13e2fa3240
		summarizeBy: none
		sourceColumn: before_packet_loss_pct

		annotation SummarizationSetBy = Automatic

	column after_packet_loss_pct
		dataType: double
		lineageTag: 46530734-a423-4d09-be50-4dca54ae5d00
		summarizeBy: none
		sourceColumn: after_packet_loss_pct

		annotation SummarizationSetBy = Automatic

	column before_network_availability_pct
		dataType: double
		lineageTag: f4ca9657-ac31-43cd-9e1e-002ce823e13d
		summarizeBy: none
		sourceColumn: before_network_availability_pct

		annotation SummarizationSetBy = Automatic

	column after_network_availability_pct
		dataType: double
		lineageTag: 207c4c02-609f-4e7c-976e-ad59c8f3edc3
		summarizeBy: none
		sourceColumn: after_network_availability_pct

		annotation SummarizationSetBy = Automatic

	column change_pue_pct
		dataType: double
		lineageTag: 16efe3f1-abb9-401c-9d8a-ca2922b82a95
		summarizeBy: none
		sourceColumn: change_pue_pct

		annotation SummarizationSetBy = Automatic

	column change_latency_ms_pct
		dataType: double
		lineageTag: 7d1ff988-687c-485f-9924-e54af83dc775
		summarizeBy: none
		sourceColumn: change_latency_ms_pct

		annotation SummarizationSetBy = Automatic

	column change_packet_loss_pct_pct
		dataType: double
		lineageTag: 13fe0eb9-86e4-4cc9-8b32-6af6dca767ab
		summarizeBy: none
		sourceColumn: change_packet_loss_pct_pct

		annotation SummarizationSetBy = Automatic

	column change_network_availability_pct_pct
		dataType: double
		lineageTag: 79370bea-d94c-4e2d-a2da-9d8b4116d8e3
		summarizeBy: none
		sourceColumn: change_network_availability_pct_pct

		annotation SummarizationSetBy = Automatic

	column modeled_downtime_cost_exposure_usd
		dataType: double
		lineageTag: 1cca6fdf-d11e-4856-93b4-437dc6fd55e5
		summarizeBy: none
		sourceColumn: modeled_downtime_cost_exposure_usd

		annotation SummarizationSetBy = Automatic

	column comparison_window_days
		dataType: int64
		lineageTag: 20064ab5-f0a8-482f-a297-2493740f45ed
		summarizeBy: none
		sourceColumn: comparison_window_days

		annotation SummarizationSetBy = Automatic

	column claim_level
		dataType: string
		lineageTag: 0cf01f5b-8dfe-44fc-bd4d-f50df4c9fadf
		summarizeBy: none
		sourceColumn: claim_level

		annotation SummarizationSetBy = Automatic

	column is_synthetic
		dataType: boolean
		lineageTag: 8fee9cf2-9df6-4f64-8023-91953c2a2e37
		summarizeBy: none
		sourceColumn: is_synthetic

		annotation SummarizationSetBy = Automatic

	column snapshot_version
		dataType: string
		lineageTag: 4b1d2622-f960-4f98-8ed4-400d3ef08513
		summarizeBy: none
		sourceColumn: snapshot_version

		annotation SummarizationSetBy = Automatic

	partition FactIncidentImpact = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/admin/Downloads/AI_Image_Classification_Final_Project_Import_Fixed/ai-data-center-intelligence/data/processed/powerbi_incident_impact_snapshot.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"incident_id", type text}, {"incident_date", type date}, {"facility_id", type text},
				        {"facility_name", type text}, {"server_id", type text}, {"severity", type text},
				        {"root_cause", type text}, {"status", type text}, {"downtime_minutes", Int64.Type},
				        {"during_pue", type number}, {"during_latency_ms", type number},
				        {"during_packet_loss_pct", type number}, {"during_network_availability_pct", type number},
				        {"before_pue", type number}, {"after_pue", type number},
				        {"before_latency_ms", type number}, {"after_latency_ms", type number},
				        {"before_packet_loss_pct", type number}, {"after_packet_loss_pct", type number},
				        {"before_network_availability_pct", type number}, {"after_network_availability_pct", type number},
				        {"change_pue_pct", type number}, {"change_latency_ms_pct", type number},
				        {"change_packet_loss_pct_pct", type number}, {"change_network_availability_pct_pct", type number},
				        {"modeled_downtime_cost_exposure_usd", type number}, {"comparison_window_days", Int64.Type},
				        {"claim_level", type text}, {"is_synthetic", type logical}, {"snapshot_version", type text}
				    })
				in
				    Typed

