table FactMaintenanceActions

	column action_id
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: action_id

		annotation SummarizationSetBy = Automatic

	column incident_id
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: incident_id

		annotation SummarizationSetBy = Automatic

	column facility_id
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: facility_id

		annotation SummarizationSetBy = Automatic

	column server_id
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: server_id

		annotation SummarizationSetBy = Automatic

	column timestamp
		dataType: dateTime
		isNullable: false
		summarizeBy: none
		sourceColumn: timestamp

		annotation SummarizationSetBy = Automatic

	column action_type
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: action_type

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column result
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: result

		annotation SummarizationSetBy = Automatic

	column performed_by_role
		dataType: string
		isNullable: false
		summarizeBy: none
		sourceColumn: performed_by_role

		annotation SummarizationSetBy = Automatic

	column action_date
		dataType: dateTime
		isNullable: false
		summarizeBy: none
		sourceColumn: action_date

		annotation SummarizationSetBy = Automatic

	partition FactMaintenanceActions = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/admin/Downloads/AI_Image_Classification_Final_Project_Import_Fixed/ai-data-center-intelligence/data/processed/maintenance_actions.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"action_id", type text}, {"incident_id", type text}, {"facility_id", type text},
				        {"server_id", type text}, {"timestamp", type datetime}, {"action_type", type text},
				        {"description", type text}, {"result", type text}, {"performed_by_role", type text}
				    }),
				    ActionDate = Table.AddColumn(Typed, "action_date", each Date.From([timestamp]), type date)
				in
				    ActionDate
