DimDate =
ADDCOLUMNS(
    CALENDAR(DATE(2015, 1, 1), DATE(2025, 12, 31)),
    "Year", YEAR([Date]),
    "Quarter Number", QUARTER([Date]),
    "Quarter", "Q" & FORMAT(QUARTER([Date]), "0"),
    "Month Number", MONTH([Date]),
    "Month", FORMAT([Date], "MMM"),
    "Month Year", FORMAT([Date], "MMM yyyy"),
    "Year Month", FORMAT([Date], "yyyy-MM"),
    "Weekday Number", WEEKDAY([Date], 2),
    "Weekday", FORMAT([Date], "ddd")
)

