SET NOCOUNT ON;
SET XACT_ABORT ON;

IF DB_ID(N'AIDecisionIntelligence') IS NULL
BEGIN
    CREATE DATABASE [AIDecisionIntelligence];
END;
GO

ALTER DATABASE [AIDecisionIntelligence] SET RECOVERY SIMPLE;
ALTER DATABASE [AIDecisionIntelligence] SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE;
GO

