SET NOCOUNT ON;
SET XACT_ABORT ON;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_DimDate_FullDate' AND object_id=OBJECT_ID(N'dbo.DimDate')) CREATE INDEX IX_DimDate_FullDate ON dbo.DimDate(FullDate);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_DimProduct_Category' AND object_id=OBJECT_ID(N'dbo.DimProduct')) CREATE INDEX IX_DimProduct_Category ON dbo.DimProduct(CategoryKey, ProductID);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_DimStore_State' AND object_id=OBJECT_ID(N'dbo.DimStore')) CREATE INDEX IX_DimStore_State ON dbo.DimStore(StateKey, StoreID);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_DimWarehouse_State' AND object_id=OBJECT_ID(N'dbo.DimWarehouse')) CREATE INDEX IX_DimWarehouse_State ON dbo.DimWarehouse(StateKey, WarehouseID);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_DimSupplier_Risk' AND object_id=OBJECT_ID(N'dbo.DimSupplier')) CREATE INDEX IX_DimSupplier_Risk ON dbo.DimSupplier(RiskLevel, ActiveFlag) INCLUDE (ReliabilityScore, BaseLeadTimeDays);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_DimScenario_Type' AND object_id=OBJECT_ID(N'dbo.DimScenario')) CREATE INDEX IX_DimScenario_Type ON dbo.DimScenario(ScenarioType, IsBaseline);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_DimModel_Production' AND object_id=OBJECT_ID(N'dbo.DimModel')) CREATE INDEX IX_DimModel_Production ON dbo.DimModel(IsProduction, ActiveFlag);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_FactSales_ProductDate' AND object_id=OBJECT_ID(N'dbo.FactSales')) CREATE INDEX IX_FactSales_ProductDate ON dbo.FactSales(ProductKey, DateKey) INCLUDE (StoreKey, Quantity, UnitPrice);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_FactSales_StoreDate' AND object_id=OBJECT_ID(N'dbo.FactSales')) CREATE INDEX IX_FactSales_StoreDate ON dbo.FactSales(StoreKey, DateKey) INCLUDE (ProductKey, Quantity);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_FactSellPrice_ProductDate' AND object_id=OBJECT_ID(N'dbo.FactSellPrice')) CREATE INDEX IX_FactSellPrice_ProductDate ON dbo.FactSellPrice(ProductKey, DateKey) INCLUDE (StoreKey, SellPrice);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_Inventory_ProductWarehouseDate' AND object_id=OBJECT_ID(N'dbo.FactInventorySnapshot')) CREATE INDEX IX_Inventory_ProductWarehouseDate ON dbo.FactInventorySnapshot(ProductKey, WarehouseKey, DateKey DESC) INCLUDE (ClosingStock, InventoryValue);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_Inventory_WarehouseDate' AND object_id=OBJECT_ID(N'dbo.FactInventorySnapshot')) CREATE INDEX IX_Inventory_WarehouseDate ON dbo.FactInventorySnapshot(WarehouseKey, DateKey) INCLUDE (ProductKey, ClosingStock);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_PO_SupplierStatusDate' AND object_id=OBJECT_ID(N'dbo.FactPurchaseOrder')) CREATE INDEX IX_PO_SupplierStatusDate ON dbo.FactPurchaseOrder(SupplierKey, Status, OrderDateKey) INCLUDE (WarehouseKey, TotalPurchaseCost);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_PO_WarehouseDate' AND object_id=OBJECT_ID(N'dbo.FactPurchaseOrder')) CREATE INDEX IX_PO_WarehouseDate ON dbo.FactPurchaseOrder(WarehouseKey, OrderDateKey) INCLUDE (SupplierKey, Status);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_POLine_Product' AND object_id=OBJECT_ID(N'dbo.FactPurchaseOrderLine')) CREATE INDEX IX_POLine_Product ON dbo.FactPurchaseOrderLine(ProductKey, PurchaseOrderKey) INCLUDE (OrderedQuantity, ReceivedQuantity, UnitCost);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_SupplierPerformance_SupplierDate' AND object_id=OBJECT_ID(N'dbo.FactSupplierPerformance')) CREATE INDEX IX_SupplierPerformance_SupplierDate ON dbo.FactSupplierPerformance(SupplierKey, DateKey DESC);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_Transportation_Warehouse' AND object_id=OBJECT_ID(N'dbo.FactTransportation')) CREATE INDEX IX_Transportation_Warehouse ON dbo.FactTransportation(WarehouseKey, PreferredLaneFlag) INCLUDE (SupplierKey, ShippingCostPerUnit);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_ModelRun_ModelStatus' AND object_id=OBJECT_ID(N'dbo.FactModelRun')) CREATE INDEX IX_ModelRun_ModelStatus ON dbo.FactModelRun(ModelKey, RunStatus, RunStartedAt DESC);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_Forecast_ProductTarget' AND object_id=OBJECT_ID(N'dbo.FactForecast')) CREATE INDEX IX_Forecast_ProductTarget ON dbo.FactForecast(ProductKey, TargetDateKey, HorizonDays) INCLUDE (ModelKey, ForecastQuantity, LowerBound, UpperBound);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_Forecast_StoreTarget' AND object_id=OBJECT_ID(N'dbo.FactForecast')) CREATE INDEX IX_Forecast_StoreTarget ON dbo.FactForecast(StoreKey, TargetDateKey) INCLUDE (ProductKey, ForecastQuantity) WHERE StoreKey IS NOT NULL;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_Forecast_WarehouseTarget' AND object_id=OBJECT_ID(N'dbo.FactForecast')) CREATE INDEX IX_Forecast_WarehouseTarget ON dbo.FactForecast(WarehouseKey, TargetDateKey) INCLUDE (ProductKey, StockoutProbability) WHERE WarehouseKey IS NOT NULL;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_Forecast_ModelHorizon' AND object_id=OBJECT_ID(N'dbo.FactForecast')) CREATE INDEX IX_Forecast_ModelHorizon ON dbo.FactForecast(ModelKey, HorizonDays, TargetDateKey);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_ForecastMetric_ModelHorizon' AND object_id=OBJECT_ID(N'dbo.FactForecastMetric')) CREATE INDEX IX_ForecastMetric_ModelHorizon ON dbo.FactForecastMetric(ModelKey, HorizonDays) INCLUDE (WAPE, RMSE, MAE, Bias);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_Explanation_ForecastRank' AND object_id=OBJECT_ID(N'dbo.FactModelExplanation')) CREATE INDEX IX_Explanation_ForecastRank ON dbo.FactModelExplanation(ForecastKey, ContributionRank) INCLUDE (FeatureName, ShapValue, Direction);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_StockoutRisk_RiskDate' AND object_id=OBJECT_ID(N'dbo.FactStockoutRisk')) CREATE INDEX IX_StockoutRisk_RiskDate ON dbo.FactStockoutRisk(RiskClassification, DateKey) INCLUDE (ProductKey, WarehouseKey, StockoutProbability);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_StockoutRisk_ProductDate' AND object_id=OBJECT_ID(N'dbo.FactStockoutRisk')) CREATE INDEX IX_StockoutRisk_ProductDate ON dbo.FactStockoutRisk(ProductKey, DateKey DESC) INCLUDE (WarehouseKey, DaysOfSupply, ReorderPoint);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_Recommendation_ProductDate' AND object_id=OBJECT_ID(N'dbo.FactOptimizationRecommendation')) CREATE INDEX IX_Recommendation_ProductDate ON dbo.FactOptimizationRecommendation(ProductKey, DateKey DESC) INCLUDE (SupplierKey, WarehouseKey, RecommendedOrderQuantity, SolverStatus);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_Recommendation_SupplierStatus' AND object_id=OBJECT_ID(N'dbo.FactOptimizationRecommendation')) CREATE INDEX IX_Recommendation_SupplierStatus ON dbo.FactOptimizationRecommendation(SupplierKey, SolverStatus, DateKey);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_Recommendation_WarehouseDate' AND object_id=OBJECT_ID(N'dbo.FactOptimizationRecommendation')) CREATE INDEX IX_Recommendation_WarehouseDate ON dbo.FactOptimizationRecommendation(WarehouseKey, DateKey) INCLUDE (ExpectedTotalCost, ExpectedRevenueProtected);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_Allocation_Recommendation' AND object_id=OBJECT_ID(N'dbo.FactOptimizationAllocation')) CREATE INDEX IX_Allocation_Recommendation ON dbo.FactOptimizationAllocation(OptimizationRecommendationKey, WarehouseKey);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_ScenarioResult_ScenarioDate' AND object_id=OBJECT_ID(N'dbo.FactScenarioResult')) CREATE INDEX IX_ScenarioResult_ScenarioDate ON dbo.FactScenarioResult(ScenarioKey, DateKey) INCLUDE (ProductKey, ScenarioRevenue, ScenarioTotalCost, ScenarioProfit);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_DataQuality_StatusDate' AND object_id=OBJECT_ID(N'dbo.FactDataQuality')) CREATE INDEX IX_DataQuality_StatusDate ON dbo.FactDataQuality(Status, CheckDateKey) INCLUDE (TableName, Severity, FailedRecords);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'IX_DataQuality_TableDate' AND object_id=OBJECT_ID(N'dbo.FactDataQuality')) CREATE INDEX IX_DataQuality_TableDate ON dbo.FactDataQuality(TableName, CheckDateKey DESC) INCLUDE (CheckName, Status, RecordsChecked);
GO
