from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class MetricDefinition:
    code: str
    name: str
    statement: str
    category: str
    tags: tuple[str, ...]
    preferred_units: tuple[str, ...]
    instant: bool = False
    derive_q4: bool = False
    non_negative: bool = False


METRICS: tuple[MetricDefinition, ...] = (
    MetricDefinition(
        "REVENUE",
        "Revenue",
        "Income Statement",
        "Profitability",
        ("RevenueFromContractWithCustomerExcludingAssessedTax", "SalesRevenueNet"),
        ("USD",),
        derive_q4=True,
        non_negative=True,
    ),
    MetricDefinition(
        "COST_OF_REVENUE",
        "Cost of Revenue",
        "Income Statement",
        "Profitability",
        ("CostOfGoodsAndServicesSold", "CostOfRevenue"),
        ("USD",),
        derive_q4=True,
        non_negative=True,
    ),
    MetricDefinition(
        "GROSS_PROFIT",
        "Gross Profit",
        "Income Statement",
        "Profitability",
        ("GrossProfit",),
        ("USD",),
        derive_q4=True,
    ),
    MetricDefinition(
        "OPERATING_EXPENSE",
        "Operating Expense",
        "Income Statement",
        "Profitability",
        ("OperatingExpenses",),
        ("USD",),
        derive_q4=True,
        non_negative=True,
    ),
    MetricDefinition(
        "OPERATING_INCOME",
        "Operating Income",
        "Income Statement",
        "Profitability",
        ("OperatingIncomeLoss",),
        ("USD",),
        derive_q4=True,
    ),
    MetricDefinition(
        "NET_INCOME",
        "Net Income",
        "Income Statement",
        "Profitability",
        ("NetIncomeLoss", "ProfitLoss"),
        ("USD",),
        derive_q4=True,
    ),
    MetricDefinition(
        "DILUTED_EPS",
        "Diluted EPS",
        "Income Statement",
        "Per Share",
        ("EarningsPerShareDiluted",),
        ("USD/shares",),
    ),
    MetricDefinition(
        "R_AND_D",
        "Research and Development",
        "Income Statement",
        "Operating Expense",
        ("ResearchAndDevelopmentExpense",),
        ("USD",),
        derive_q4=True,
        non_negative=True,
    ),
    MetricDefinition(
        "SG_AND_A",
        "Selling, General and Administrative",
        "Income Statement",
        "Operating Expense",
        ("SellingGeneralAndAdministrativeExpense",),
        ("USD",),
        derive_q4=True,
        non_negative=True,
    ),
    MetricDefinition(
        "TOTAL_ASSETS",
        "Total Assets",
        "Balance Sheet",
        "Financial Position",
        ("Assets",),
        ("USD",),
        instant=True,
        non_negative=True,
    ),
    MetricDefinition(
        "TOTAL_LIABILITIES",
        "Total Liabilities",
        "Balance Sheet",
        "Financial Position",
        ("Liabilities",),
        ("USD",),
        instant=True,
        non_negative=True,
    ),
    MetricDefinition(
        "EQUITY",
        "Shareholders' Equity",
        "Balance Sheet",
        "Financial Position",
        ("StockholdersEquity",),
        ("USD",),
        instant=True,
    ),
    MetricDefinition(
        "CASH",
        "Cash and Cash Equivalents",
        "Balance Sheet",
        "Liquidity",
        ("CashAndCashEquivalentsAtCarryingValue",),
        ("USD",),
        instant=True,
        non_negative=True,
    ),
    MetricDefinition(
        "INVENTORY",
        "Inventory",
        "Balance Sheet",
        "Working Capital",
        ("InventoryNet",),
        ("USD",),
        instant=True,
        non_negative=True,
    ),
    MetricDefinition(
        "ACCOUNTS_RECEIVABLE",
        "Accounts Receivable",
        "Balance Sheet",
        "Working Capital",
        ("AccountsReceivableNetCurrent",),
        ("USD",),
        instant=True,
        non_negative=True,
    ),
    MetricDefinition(
        "CURRENT_ASSETS",
        "Current Assets",
        "Balance Sheet",
        "Liquidity",
        ("AssetsCurrent",),
        ("USD",),
        instant=True,
        non_negative=True,
    ),
    MetricDefinition(
        "CURRENT_LIABILITIES",
        "Current Liabilities",
        "Balance Sheet",
        "Liquidity",
        ("LiabilitiesCurrent",),
        ("USD",),
        instant=True,
        non_negative=True,
    ),
    MetricDefinition(
        "OPERATING_CASH_FLOW",
        "Operating Cash Flow",
        "Cash Flow Statement",
        "Cash Flow",
        ("NetCashProvidedByUsedInOperatingActivities",),
        ("USD",),
        derive_q4=True,
    ),
    MetricDefinition(
        "CAPEX",
        "Capital Expenditure",
        "Cash Flow Statement",
        "Cash Flow",
        ("PaymentsToAcquirePropertyPlantAndEquipment",),
        ("USD",),
        derive_q4=True,
        non_negative=True,
    ),
    MetricDefinition(
        "DIVIDENDS_PAID",
        "Dividends Paid",
        "Cash Flow Statement",
        "Financing",
        ("PaymentsOfDividends", "PaymentsOfDividendsCommonStock"),
        ("USD",),
        derive_q4=True,
        non_negative=True,
    ),
    MetricDefinition(
        "SHARE_REPURCHASES",
        "Share Repurchases",
        "Cash Flow Statement",
        "Financing",
        ("PaymentsForRepurchaseOfCommonStock",),
        ("USD",),
        derive_q4=True,
        non_negative=True,
    ),
)

METRIC_BY_CODE = {metric.code: metric for metric in METRICS}
